// Code generated by mockery v1.0.0. DO NOT EDIT.

package jsonrpcmocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// Invoke provides a mock function with given fields: ctx, result, method, params
func (_m *Client) Invoke(ctx context.Context, result interface{}, method string, params ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, ctx, result, method)
	_ca = append(_ca, params...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, string, ...interface{}) error); ok {
		r0 = rf(ctx, result, method, params...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
