// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package rpcbackendmocks

import (
	"context"

	"github.com/hyperledger-firefly/signer/pkg/rpcbackend"
	mock "github.com/stretchr/testify/mock"
)

// NewBackend creates a new instance of Backend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBackend(t interface {
	mock.TestingT
	Cleanup(func())
}) *Backend {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &Backend{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// Backend is an autogenerated mock type for the Backend type
type Backend struct {
	mock.Mock
}

type Backend_Expecter struct {
	mock *mock.Mock
}

func (_m *Backend) EXPECT() *Backend_Expecter {
	return &Backend_Expecter{mock: &_m.Mock}
}

// CallRPC provides a mock function for the type Backend
func (_mock *Backend) CallRPC(ctx context.Context, result interface{}, method string, params ...interface{}) *rpcbackend.RPCError {
	var _ca []any
	_ca = append(_ca, ctx, result, method)
	_ca = append(_ca, params...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CallRPC")
	}

	var r0 *rpcbackend.RPCError
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, string, ...interface{}) *rpcbackend.RPCError); ok {
		r0 = returnFunc(ctx, result, method, params...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rpcbackend.RPCError)
		}
	}
	return r0
}

// Backend_CallRPC_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CallRPC'
type Backend_CallRPC_Call struct {
	*mock.Call
}

// CallRPC is a helper method to define mock.On call
//   - ctx context.Context
//   - result interface{}
//   - method string
//   - params ...interface{}
func (_e *Backend_Expecter) CallRPC(ctx any, result any, method any, params ...any) *Backend_CallRPC_Call {
	return &Backend_CallRPC_Call{Call: _e.mock.On("CallRPC",
		append([]any{ctx, result, method}, params...)...)}
}

func (_c *Backend_CallRPC_Call) Run(run func(ctx context.Context, result interface{}, method string, params ...interface{})) *Backend_CallRPC_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []interface{}
		variadicArgs := make([]interface{}, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *Backend_CallRPC_Call) Return(rPCError *rpcbackend.RPCError) *Backend_CallRPC_Call {
	_c.Call.Return(rPCError)
	return _c
}

func (_c *Backend_CallRPC_Call) RunAndReturn(run func(ctx context.Context, result interface{}, method string, params ...interface{}) *rpcbackend.RPCError) *Backend_CallRPC_Call {
	_c.Call.Return(run)
	return _c
}

// CallRPCBatch provides a mock function for the type Backend
func (_mock *Backend) CallRPCBatch(ctx context.Context, ops ...*rpcbackend.RPCBatchOp) []*rpcbackend.RPCError {
	// *rpcbackend.RPCBatchOp
	_va := make([]any, len(ops))
	for _i := range ops {
		_va[_i] = ops[_i]
	}
	var _ca []any
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CallRPCBatch")
	}

	var r0 []*rpcbackend.RPCError
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...*rpcbackend.RPCBatchOp) []*rpcbackend.RPCError); ok {
		r0 = returnFunc(ctx, ops...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*rpcbackend.RPCError)
		}
	}
	return r0
}

// Backend_CallRPCBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CallRPCBatch'
type Backend_CallRPCBatch_Call struct {
	*mock.Call
}

// CallRPCBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - ops ...*rpcbackend.RPCBatchOp
func (_e *Backend_Expecter) CallRPCBatch(ctx any, ops ...any) *Backend_CallRPCBatch_Call {
	return &Backend_CallRPCBatch_Call{Call: _e.mock.On("CallRPCBatch",
		append([]any{ctx}, ops...)...)}
}

func (_c *Backend_CallRPCBatch_Call) Run(run func(ctx context.Context, ops ...*rpcbackend.RPCBatchOp)) *Backend_CallRPCBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*rpcbackend.RPCBatchOp
		variadicArgs := make([]*rpcbackend.RPCBatchOp, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(*rpcbackend.RPCBatchOp)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Backend_CallRPCBatch_Call) Return(rPCErrors []*rpcbackend.RPCError) *Backend_CallRPCBatch_Call {
	_c.Call.Return(rPCErrors)
	return _c
}

func (_c *Backend_CallRPCBatch_Call) RunAndReturn(run func(ctx context.Context, ops ...*rpcbackend.RPCBatchOp) []*rpcbackend.RPCError) *Backend_CallRPCBatch_Call {
	_c.Call.Return(run)
	return _c
}

// SyncRequest provides a mock function for the type Backend
func (_mock *Backend) SyncRequest(ctx context.Context, rpcReq *rpcbackend.RPCRequest) (*rpcbackend.RPCResponse, error) {
	ret := _mock.Called(ctx, rpcReq)

	if len(ret) == 0 {
		panic("no return value specified for SyncRequest")
	}

	var r0 *rpcbackend.RPCResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *rpcbackend.RPCRequest) (*rpcbackend.RPCResponse, error)); ok {
		return returnFunc(ctx, rpcReq)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *rpcbackend.RPCRequest) *rpcbackend.RPCResponse); ok {
		r0 = returnFunc(ctx, rpcReq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rpcbackend.RPCResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *rpcbackend.RPCRequest) error); ok {
		r1 = returnFunc(ctx, rpcReq)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Backend_SyncRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncRequest'
type Backend_SyncRequest_Call struct {
	*mock.Call
}

// SyncRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - rpcReq *rpcbackend.RPCRequest
func (_e *Backend_Expecter) SyncRequest(ctx any, rpcReq any) *Backend_SyncRequest_Call {
	return &Backend_SyncRequest_Call{Call: _e.mock.On("SyncRequest", ctx, rpcReq)}
}

func (_c *Backend_SyncRequest_Call) Run(run func(ctx context.Context, rpcReq *rpcbackend.RPCRequest)) *Backend_SyncRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *rpcbackend.RPCRequest
		if args[1] != nil {
			arg1 = args[1].(*rpcbackend.RPCRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Backend_SyncRequest_Call) Return(rpcRes *rpcbackend.RPCResponse, err error) *Backend_SyncRequest_Call {
	_c.Call.Return(rpcRes, err)
	return _c
}

func (_c *Backend_SyncRequest_Call) RunAndReturn(run func(ctx context.Context, rpcReq *rpcbackend.RPCRequest) (*rpcbackend.RPCResponse, error)) *Backend_SyncRequest_Call {
	_c.Call.Return(run)
	return _c
}
