// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package rpcbackendmocks

import (
	"context"

	"github.com/hyperledger-firefly/common/pkg/fftypes"
	"github.com/hyperledger-firefly/signer/pkg/rpcbackend"
	mock "github.com/stretchr/testify/mock"
)

// NewSubscription creates a new instance of Subscription. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSubscription(t interface {
	mock.TestingT
	Cleanup(func())
}) *Subscription {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &Subscription{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// Subscription is an autogenerated mock type for the Subscription type
type Subscription struct {
	mock.Mock
}

type Subscription_Expecter struct {
	mock *mock.Mock
}

func (_m *Subscription) EXPECT() *Subscription_Expecter {
	return &Subscription_Expecter{mock: &_m.Mock}
}

// LocalID provides a mock function for the type Subscription
func (_mock *Subscription) LocalID() *fftypes.UUID {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for LocalID")
	}

	var r0 *fftypes.UUID
	if returnFunc, ok := ret.Get(0).(func() *fftypes.UUID); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*fftypes.UUID)
		}
	}
	return r0
}

// Subscription_LocalID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LocalID'
type Subscription_LocalID_Call struct {
	*mock.Call
}

// LocalID is a helper method to define mock.On call
func (_e *Subscription_Expecter) LocalID() *Subscription_LocalID_Call {
	return &Subscription_LocalID_Call{Call: _e.mock.On("LocalID")}
}

func (_c *Subscription_LocalID_Call) Run(run func()) *Subscription_LocalID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Subscription_LocalID_Call) Return(uUID *fftypes.UUID) *Subscription_LocalID_Call {
	_c.Call.Return(uUID)
	return _c
}

func (_c *Subscription_LocalID_Call) RunAndReturn(run func() *fftypes.UUID) *Subscription_LocalID_Call {
	_c.Call.Return(run)
	return _c
}

// Notifications provides a mock function for the type Subscription
func (_mock *Subscription) Notifications() chan *rpcbackend.RPCSubscriptionNotification {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Notifications")
	}

	var r0 chan *rpcbackend.RPCSubscriptionNotification
	if returnFunc, ok := ret.Get(0).(func() chan *rpcbackend.RPCSubscriptionNotification); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan *rpcbackend.RPCSubscriptionNotification)
		}
	}
	return r0
}

// Subscription_Notifications_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Notifications'
type Subscription_Notifications_Call struct {
	*mock.Call
}

// Notifications is a helper method to define mock.On call
func (_e *Subscription_Expecter) Notifications() *Subscription_Notifications_Call {
	return &Subscription_Notifications_Call{Call: _e.mock.On("Notifications")}
}

func (_c *Subscription_Notifications_Call) Run(run func()) *Subscription_Notifications_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Subscription_Notifications_Call) Return(rPCSubscriptionNotificationCh chan *rpcbackend.RPCSubscriptionNotification) *Subscription_Notifications_Call {
	_c.Call.Return(rPCSubscriptionNotificationCh)
	return _c
}

func (_c *Subscription_Notifications_Call) RunAndReturn(run func() chan *rpcbackend.RPCSubscriptionNotification) *Subscription_Notifications_Call {
	_c.Call.Return(run)
	return _c
}

// Unsubscribe provides a mock function for the type Subscription
func (_mock *Subscription) Unsubscribe(ctx context.Context) *rpcbackend.RPCError {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Unsubscribe")
	}

	var r0 *rpcbackend.RPCError
	if returnFunc, ok := ret.Get(0).(func(context.Context) *rpcbackend.RPCError); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rpcbackend.RPCError)
		}
	}
	return r0
}

// Subscription_Unsubscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unsubscribe'
type Subscription_Unsubscribe_Call struct {
	*mock.Call
}

// Unsubscribe is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Subscription_Expecter) Unsubscribe(ctx any) *Subscription_Unsubscribe_Call {
	return &Subscription_Unsubscribe_Call{Call: _e.mock.On("Unsubscribe", ctx)}
}

func (_c *Subscription_Unsubscribe_Call) Run(run func(ctx context.Context)) *Subscription_Unsubscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Subscription_Unsubscribe_Call) Return(rPCError *rpcbackend.RPCError) *Subscription_Unsubscribe_Call {
	_c.Call.Return(rPCError)
	return _c
}

func (_c *Subscription_Unsubscribe_Call) RunAndReturn(run func(ctx context.Context) *rpcbackend.RPCError) *Subscription_Unsubscribe_Call {
	_c.Call.Return(run)
	return _c
}
