// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ethblocklistenermocks

import (
	"context"

	"github.com/hyperledger-firefly/common/pkg/fftypes"
	"github.com/hyperledger-firefly/common/pkg/metric"
	"github.com/hyperledger-firefly/evmconnect/pkg/ethblocklistener"
	"github.com/hyperledger-firefly/evmconnect/pkg/ethrpc"
	"github.com/hyperledger-firefly/signer/pkg/ethtypes"
	mock "github.com/stretchr/testify/mock"
)

// NewBlockListener creates a new instance of BlockListener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBlockListener(t interface {
	mock.TestingT
	Cleanup(func())
}) *BlockListener {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &BlockListener{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// BlockListener is an autogenerated mock type for the BlockListener type
type BlockListener struct {
	mock.Mock
}

type BlockListener_Expecter struct {
	mock *mock.Mock
}

func (_m *BlockListener) EXPECT() *BlockListener_Expecter {
	return &BlockListener_Expecter{mock: &_m.Mock}
}

// AddConsumer provides a mock function for the type BlockListener
func (_mock *BlockListener) AddConsumer(ctx context.Context, c *ethblocklistener.BlockUpdateConsumer) {
	_mock.Called(ctx, c)
	return
}

// BlockListener_AddConsumer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddConsumer'
type BlockListener_AddConsumer_Call struct {
	*mock.Call
}

// AddConsumer is a helper method to define mock.On call
//   - ctx context.Context
//   - c *ethblocklistener.BlockUpdateConsumer
func (_e *BlockListener_Expecter) AddConsumer(ctx any, c any) *BlockListener_AddConsumer_Call {
	return &BlockListener_AddConsumer_Call{Call: _e.mock.On("AddConsumer", ctx, c)}
}

func (_c *BlockListener_AddConsumer_Call) Run(run func(ctx context.Context, c *ethblocklistener.BlockUpdateConsumer)) *BlockListener_AddConsumer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ethblocklistener.BlockUpdateConsumer
		if args[1] != nil {
			arg1 = args[1].(*ethblocklistener.BlockUpdateConsumer)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *BlockListener_AddConsumer_Call) Return() *BlockListener_AddConsumer_Call {
	_c.Call.Return()
	return _c
}

func (_c *BlockListener_AddConsumer_Call) RunAndReturn(run func(ctx context.Context, c *ethblocklistener.BlockUpdateConsumer)) *BlockListener_AddConsumer_Call {
	_c.Run(run)
	return _c
}

// FetchBlockReceiptsAsync provides a mock function for the type BlockListener
func (_mock *BlockListener) FetchBlockReceiptsAsync(blockNumber uint64, blockHash ethtypes.HexBytes0xPrefix, cb func([]*ethrpc.TxReceiptJSONRPC, error)) {
	_mock.Called(blockNumber, blockHash, cb)
	return
}

// BlockListener_FetchBlockReceiptsAsync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchBlockReceiptsAsync'
type BlockListener_FetchBlockReceiptsAsync_Call struct {
	*mock.Call
}

// FetchBlockReceiptsAsync is a helper method to define mock.On call
//   - blockNumber uint64
//   - blockHash ethtypes.HexBytes0xPrefix
//   - cb func([]*ethrpc.TxReceiptJSONRPC, error)
func (_e *BlockListener_Expecter) FetchBlockReceiptsAsync(blockNumber any, blockHash any, cb any) *BlockListener_FetchBlockReceiptsAsync_Call {
	return &BlockListener_FetchBlockReceiptsAsync_Call{Call: _e.mock.On("FetchBlockReceiptsAsync", blockNumber, blockHash, cb)}
}

func (_c *BlockListener_FetchBlockReceiptsAsync_Call) Run(run func(blockNumber uint64, blockHash ethtypes.HexBytes0xPrefix, cb func([]*ethrpc.TxReceiptJSONRPC, error))) *BlockListener_FetchBlockReceiptsAsync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 ethtypes.HexBytes0xPrefix
		if args[1] != nil {
			arg1 = args[1].(ethtypes.HexBytes0xPrefix)
		}
		var arg2 func([]*ethrpc.TxReceiptJSONRPC, error)
		if args[2] != nil {
			arg2 = args[2].(func([]*ethrpc.TxReceiptJSONRPC, error))
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *BlockListener_FetchBlockReceiptsAsync_Call) Return() *BlockListener_FetchBlockReceiptsAsync_Call {
	_c.Call.Return()
	return _c
}

func (_c *BlockListener_FetchBlockReceiptsAsync_Call) RunAndReturn(run func(blockNumber uint64, blockHash ethtypes.HexBytes0xPrefix, cb func([]*ethrpc.TxReceiptJSONRPC, error))) *BlockListener_FetchBlockReceiptsAsync_Call {
	_c.Run(run)
	return _c
}

// GetBlockGasLimit provides a mock function for the type BlockListener
func (_mock *BlockListener) GetBlockGasLimit() *ethtypes.HexInteger {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBlockGasLimit")
	}

	var r0 *ethtypes.HexInteger
	if returnFunc, ok := ret.Get(0).(func() *ethtypes.HexInteger); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ethtypes.HexInteger)
		}
	}
	return r0
}

// BlockListener_GetBlockGasLimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlockGasLimit'
type BlockListener_GetBlockGasLimit_Call struct {
	*mock.Call
}

// GetBlockGasLimit is a helper method to define mock.On call
func (_e *BlockListener_Expecter) GetBlockGasLimit() *BlockListener_GetBlockGasLimit_Call {
	return &BlockListener_GetBlockGasLimit_Call{Call: _e.mock.On("GetBlockGasLimit")}
}

func (_c *BlockListener_GetBlockGasLimit_Call) Run(run func()) *BlockListener_GetBlockGasLimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *BlockListener_GetBlockGasLimit_Call) Return(hexInteger *ethtypes.HexInteger) *BlockListener_GetBlockGasLimit_Call {
	_c.Call.Return(hexInteger)
	return _c
}

func (_c *BlockListener_GetBlockGasLimit_Call) RunAndReturn(run func() *ethtypes.HexInteger) *BlockListener_GetBlockGasLimit_Call {
	_c.Call.Return(run)
	return _c
}

// GetBlockInfoByHash provides a mock function for the type BlockListener
func (_mock *BlockListener) GetBlockInfoByHash(ctx context.Context, hash0xString string) (*ethrpc.BlockInfoJSONRPC, error) {
	ret := _mock.Called(ctx, hash0xString)

	if len(ret) == 0 {
		panic("no return value specified for GetBlockInfoByHash")
	}

	var r0 *ethrpc.BlockInfoJSONRPC
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*ethrpc.BlockInfoJSONRPC, error)); ok {
		return returnFunc(ctx, hash0xString)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *ethrpc.BlockInfoJSONRPC); ok {
		r0 = returnFunc(ctx, hash0xString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ethrpc.BlockInfoJSONRPC)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, hash0xString)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BlockListener_GetBlockInfoByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlockInfoByHash'
type BlockListener_GetBlockInfoByHash_Call struct {
	*mock.Call
}

// GetBlockInfoByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - hash0xString string
func (_e *BlockListener_Expecter) GetBlockInfoByHash(ctx any, hash0xString any) *BlockListener_GetBlockInfoByHash_Call {
	return &BlockListener_GetBlockInfoByHash_Call{Call: _e.mock.On("GetBlockInfoByHash", ctx, hash0xString)}
}

func (_c *BlockListener_GetBlockInfoByHash_Call) Run(run func(ctx context.Context, hash0xString string)) *BlockListener_GetBlockInfoByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *BlockListener_GetBlockInfoByHash_Call) Return(blockInfoJSONRPC *ethrpc.BlockInfoJSONRPC, err error) *BlockListener_GetBlockInfoByHash_Call {
	_c.Call.Return(blockInfoJSONRPC, err)
	return _c
}

func (_c *BlockListener_GetBlockInfoByHash_Call) RunAndReturn(run func(ctx context.Context, hash0xString string) (*ethrpc.BlockInfoJSONRPC, error)) *BlockListener_GetBlockInfoByHash_Call {
	_c.Call.Return(run)
	return _c
}

// GetBlockInfoByNumber provides a mock function for the type BlockListener
func (_mock *BlockListener) GetBlockInfoByNumber(ctx context.Context, blockNumber uint64, allowCache bool, expectedParentHashStr string, expectedBlockHashStr string) (*ethrpc.BlockInfoJSONRPC, error) {
	ret := _mock.Called(ctx, blockNumber, allowCache, expectedParentHashStr, expectedBlockHashStr)

	if len(ret) == 0 {
		panic("no return value specified for GetBlockInfoByNumber")
	}

	var r0 *ethrpc.BlockInfoJSONRPC
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, bool, string, string) (*ethrpc.BlockInfoJSONRPC, error)); ok {
		return returnFunc(ctx, blockNumber, allowCache, expectedParentHashStr, expectedBlockHashStr)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, bool, string, string) *ethrpc.BlockInfoJSONRPC); ok {
		r0 = returnFunc(ctx, blockNumber, allowCache, expectedParentHashStr, expectedBlockHashStr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ethrpc.BlockInfoJSONRPC)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, bool, string, string) error); ok {
		r1 = returnFunc(ctx, blockNumber, allowCache, expectedParentHashStr, expectedBlockHashStr)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BlockListener_GetBlockInfoByNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlockInfoByNumber'
type BlockListener_GetBlockInfoByNumber_Call struct {
	*mock.Call
}

// GetBlockInfoByNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - blockNumber uint64
//   - allowCache bool
//   - expectedParentHashStr string
//   - expectedBlockHashStr string
func (_e *BlockListener_Expecter) GetBlockInfoByNumber(ctx any, blockNumber any, allowCache any, expectedParentHashStr any, expectedBlockHashStr any) *BlockListener_GetBlockInfoByNumber_Call {
	return &BlockListener_GetBlockInfoByNumber_Call{Call: _e.mock.On("GetBlockInfoByNumber", ctx, blockNumber, allowCache, expectedParentHashStr, expectedBlockHashStr)}
}

func (_c *BlockListener_GetBlockInfoByNumber_Call) Run(run func(ctx context.Context, blockNumber uint64, allowCache bool, expectedParentHashStr string, expectedBlockHashStr string)) *BlockListener_GetBlockInfoByNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *BlockListener_GetBlockInfoByNumber_Call) Return(blockInfoJSONRPC *ethrpc.BlockInfoJSONRPC, err error) *BlockListener_GetBlockInfoByNumber_Call {
	_c.Call.Return(blockInfoJSONRPC, err)
	return _c
}

func (_c *BlockListener_GetBlockInfoByNumber_Call) RunAndReturn(run func(ctx context.Context, blockNumber uint64, allowCache bool, expectedParentHashStr string, expectedBlockHashStr string) (*ethrpc.BlockInfoJSONRPC, error)) *BlockListener_GetBlockInfoByNumber_Call {
	_c.Call.Return(run)
	return _c
}

// GetEVMBlockWithTransactionsByHash provides a mock function for the type BlockListener
func (_mock *BlockListener) GetEVMBlockWithTransactionsByHash(ctx context.Context, hash0xString string) (*ethrpc.EVMBlockWithTransactionsJSONRPC, error) {
	ret := _mock.Called(ctx, hash0xString)

	if len(ret) == 0 {
		panic("no return value specified for GetEVMBlockWithTransactionsByHash")
	}

	var r0 *ethrpc.EVMBlockWithTransactionsJSONRPC
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*ethrpc.EVMBlockWithTransactionsJSONRPC, error)); ok {
		return returnFunc(ctx, hash0xString)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *ethrpc.EVMBlockWithTransactionsJSONRPC); ok {
		r0 = returnFunc(ctx, hash0xString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ethrpc.EVMBlockWithTransactionsJSONRPC)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, hash0xString)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BlockListener_GetEVMBlockWithTransactionsByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEVMBlockWithTransactionsByHash'
type BlockListener_GetEVMBlockWithTransactionsByHash_Call struct {
	*mock.Call
}

// GetEVMBlockWithTransactionsByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - hash0xString string
func (_e *BlockListener_Expecter) GetEVMBlockWithTransactionsByHash(ctx any, hash0xString any) *BlockListener_GetEVMBlockWithTransactionsByHash_Call {
	return &BlockListener_GetEVMBlockWithTransactionsByHash_Call{Call: _e.mock.On("GetEVMBlockWithTransactionsByHash", ctx, hash0xString)}
}

func (_c *BlockListener_GetEVMBlockWithTransactionsByHash_Call) Run(run func(ctx context.Context, hash0xString string)) *BlockListener_GetEVMBlockWithTransactionsByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *BlockListener_GetEVMBlockWithTransactionsByHash_Call) Return(b *ethrpc.EVMBlockWithTransactionsJSONRPC, err error) *BlockListener_GetEVMBlockWithTransactionsByHash_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *BlockListener_GetEVMBlockWithTransactionsByHash_Call) RunAndReturn(run func(ctx context.Context, hash0xString string) (*ethrpc.EVMBlockWithTransactionsJSONRPC, error)) *BlockListener_GetEVMBlockWithTransactionsByHash_Call {
	_c.Call.Return(run)
	return _c
}

// GetEVMBlockWithTransactionsByNumber provides a mock function for the type BlockListener
func (_mock *BlockListener) GetEVMBlockWithTransactionsByNumber(ctx context.Context, numberLookup string) (*ethrpc.EVMBlockWithTransactionsJSONRPC, error) {
	ret := _mock.Called(ctx, numberLookup)

	if len(ret) == 0 {
		panic("no return value specified for GetEVMBlockWithTransactionsByNumber")
	}

	var r0 *ethrpc.EVMBlockWithTransactionsJSONRPC
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*ethrpc.EVMBlockWithTransactionsJSONRPC, error)); ok {
		return returnFunc(ctx, numberLookup)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *ethrpc.EVMBlockWithTransactionsJSONRPC); ok {
		r0 = returnFunc(ctx, numberLookup)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ethrpc.EVMBlockWithTransactionsJSONRPC)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, numberLookup)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BlockListener_GetEVMBlockWithTransactionsByNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEVMBlockWithTransactionsByNumber'
type BlockListener_GetEVMBlockWithTransactionsByNumber_Call struct {
	*mock.Call
}

// GetEVMBlockWithTransactionsByNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - numberLookup string
func (_e *BlockListener_Expecter) GetEVMBlockWithTransactionsByNumber(ctx any, numberLookup any) *BlockListener_GetEVMBlockWithTransactionsByNumber_Call {
	return &BlockListener_GetEVMBlockWithTransactionsByNumber_Call{Call: _e.mock.On("GetEVMBlockWithTransactionsByNumber", ctx, numberLookup)}
}

func (_c *BlockListener_GetEVMBlockWithTransactionsByNumber_Call) Run(run func(ctx context.Context, numberLookup string)) *BlockListener_GetEVMBlockWithTransactionsByNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *BlockListener_GetEVMBlockWithTransactionsByNumber_Call) Return(b *ethrpc.EVMBlockWithTransactionsJSONRPC, err error) *BlockListener_GetEVMBlockWithTransactionsByNumber_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *BlockListener_GetEVMBlockWithTransactionsByNumber_Call) RunAndReturn(run func(ctx context.Context, numberLookup string) (*ethrpc.EVMBlockWithTransactionsJSONRPC, error)) *BlockListener_GetEVMBlockWithTransactionsByNumber_Call {
	_c.Call.Return(run)
	return _c
}

// GetEVMBlockWithTxHashesByHash provides a mock function for the type BlockListener
func (_mock *BlockListener) GetEVMBlockWithTxHashesByHash(ctx context.Context, hash0xString string) (*ethrpc.EVMBlockWithTxHashesJSONRPC, error) {
	ret := _mock.Called(ctx, hash0xString)

	if len(ret) == 0 {
		panic("no return value specified for GetEVMBlockWithTxHashesByHash")
	}

	var r0 *ethrpc.EVMBlockWithTxHashesJSONRPC
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*ethrpc.EVMBlockWithTxHashesJSONRPC, error)); ok {
		return returnFunc(ctx, hash0xString)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *ethrpc.EVMBlockWithTxHashesJSONRPC); ok {
		r0 = returnFunc(ctx, hash0xString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ethrpc.EVMBlockWithTxHashesJSONRPC)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, hash0xString)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BlockListener_GetEVMBlockWithTxHashesByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEVMBlockWithTxHashesByHash'
type BlockListener_GetEVMBlockWithTxHashesByHash_Call struct {
	*mock.Call
}

// GetEVMBlockWithTxHashesByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - hash0xString string
func (_e *BlockListener_Expecter) GetEVMBlockWithTxHashesByHash(ctx any, hash0xString any) *BlockListener_GetEVMBlockWithTxHashesByHash_Call {
	return &BlockListener_GetEVMBlockWithTxHashesByHash_Call{Call: _e.mock.On("GetEVMBlockWithTxHashesByHash", ctx, hash0xString)}
}

func (_c *BlockListener_GetEVMBlockWithTxHashesByHash_Call) Run(run func(ctx context.Context, hash0xString string)) *BlockListener_GetEVMBlockWithTxHashesByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *BlockListener_GetEVMBlockWithTxHashesByHash_Call) Return(b *ethrpc.EVMBlockWithTxHashesJSONRPC, err error) *BlockListener_GetEVMBlockWithTxHashesByHash_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *BlockListener_GetEVMBlockWithTxHashesByHash_Call) RunAndReturn(run func(ctx context.Context, hash0xString string) (*ethrpc.EVMBlockWithTxHashesJSONRPC, error)) *BlockListener_GetEVMBlockWithTxHashesByHash_Call {
	_c.Call.Return(run)
	return _c
}

// GetEVMBlockWithTxHashesByNumber provides a mock function for the type BlockListener
func (_mock *BlockListener) GetEVMBlockWithTxHashesByNumber(ctx context.Context, numberLookup string) (*ethrpc.EVMBlockWithTxHashesJSONRPC, error) {
	ret := _mock.Called(ctx, numberLookup)

	if len(ret) == 0 {
		panic("no return value specified for GetEVMBlockWithTxHashesByNumber")
	}

	var r0 *ethrpc.EVMBlockWithTxHashesJSONRPC
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*ethrpc.EVMBlockWithTxHashesJSONRPC, error)); ok {
		return returnFunc(ctx, numberLookup)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *ethrpc.EVMBlockWithTxHashesJSONRPC); ok {
		r0 = returnFunc(ctx, numberLookup)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ethrpc.EVMBlockWithTxHashesJSONRPC)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, numberLookup)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BlockListener_GetEVMBlockWithTxHashesByNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEVMBlockWithTxHashesByNumber'
type BlockListener_GetEVMBlockWithTxHashesByNumber_Call struct {
	*mock.Call
}

// GetEVMBlockWithTxHashesByNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - numberLookup string
func (_e *BlockListener_Expecter) GetEVMBlockWithTxHashesByNumber(ctx any, numberLookup any) *BlockListener_GetEVMBlockWithTxHashesByNumber_Call {
	return &BlockListener_GetEVMBlockWithTxHashesByNumber_Call{Call: _e.mock.On("GetEVMBlockWithTxHashesByNumber", ctx, numberLookup)}
}

func (_c *BlockListener_GetEVMBlockWithTxHashesByNumber_Call) Run(run func(ctx context.Context, numberLookup string)) *BlockListener_GetEVMBlockWithTxHashesByNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *BlockListener_GetEVMBlockWithTxHashesByNumber_Call) Return(b *ethrpc.EVMBlockWithTxHashesJSONRPC, err error) *BlockListener_GetEVMBlockWithTxHashesByNumber_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *BlockListener_GetEVMBlockWithTxHashesByNumber_Call) RunAndReturn(run func(ctx context.Context, numberLookup string) (*ethrpc.EVMBlockWithTxHashesJSONRPC, error)) *BlockListener_GetEVMBlockWithTxHashesByNumber_Call {
	_c.Call.Return(run)
	return _c
}

// GetHighestBlock provides a mock function for the type BlockListener
func (_mock *BlockListener) GetHighestBlock(ctx context.Context) (uint64, bool) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetHighestBlock")
	}

	var r0 uint64
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context) (uint64, bool)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) uint64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) bool); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// BlockListener_GetHighestBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHighestBlock'
type BlockListener_GetHighestBlock_Call struct {
	*mock.Call
}

// GetHighestBlock is a helper method to define mock.On call
//   - ctx context.Context
func (_e *BlockListener_Expecter) GetHighestBlock(ctx any) *BlockListener_GetHighestBlock_Call {
	return &BlockListener_GetHighestBlock_Call{Call: _e.mock.On("GetHighestBlock", ctx)}
}

func (_c *BlockListener_GetHighestBlock_Call) Run(run func(ctx context.Context)) *BlockListener_GetHighestBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *BlockListener_GetHighestBlock_Call) Return(v uint64, b bool) *BlockListener_GetHighestBlock_Call {
	_c.Call.Return(v, b)
	return _c
}

func (_c *BlockListener_GetHighestBlock_Call) RunAndReturn(run func(ctx context.Context) (uint64, bool)) *BlockListener_GetHighestBlock_Call {
	_c.Call.Return(run)
	return _c
}

// GetHighestBlockInfo provides a mock function for the type BlockListener
func (_mock *BlockListener) GetHighestBlockInfo(ctx context.Context) (*ethrpc.BlockInfoJSONRPC, bool) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetHighestBlockInfo")
	}

	var r0 *ethrpc.BlockInfoJSONRPC
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*ethrpc.BlockInfoJSONRPC, bool)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *ethrpc.BlockInfoJSONRPC); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ethrpc.BlockInfoJSONRPC)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) bool); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// BlockListener_GetHighestBlockInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHighestBlockInfo'
type BlockListener_GetHighestBlockInfo_Call struct {
	*mock.Call
}

// GetHighestBlockInfo is a helper method to define mock.On call
//   - ctx context.Context
func (_e *BlockListener_Expecter) GetHighestBlockInfo(ctx any) *BlockListener_GetHighestBlockInfo_Call {
	return &BlockListener_GetHighestBlockInfo_Call{Call: _e.mock.On("GetHighestBlockInfo", ctx)}
}

func (_c *BlockListener_GetHighestBlockInfo_Call) Run(run func(ctx context.Context)) *BlockListener_GetHighestBlockInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *BlockListener_GetHighestBlockInfo_Call) Return(blockInfoJSONRPC *ethrpc.BlockInfoJSONRPC, b bool) *BlockListener_GetHighestBlockInfo_Call {
	_c.Call.Return(blockInfoJSONRPC, b)
	return _c
}

func (_c *BlockListener_GetHighestBlockInfo_Call) RunAndReturn(run func(ctx context.Context) (*ethrpc.BlockInfoJSONRPC, bool)) *BlockListener_GetHighestBlockInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetMonitoredHeadLength provides a mock function for the type BlockListener
func (_mock *BlockListener) GetMonitoredHeadLength() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMonitoredHeadLength")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// BlockListener_GetMonitoredHeadLength_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMonitoredHeadLength'
type BlockListener_GetMonitoredHeadLength_Call struct {
	*mock.Call
}

// GetMonitoredHeadLength is a helper method to define mock.On call
func (_e *BlockListener_Expecter) GetMonitoredHeadLength() *BlockListener_GetMonitoredHeadLength_Call {
	return &BlockListener_GetMonitoredHeadLength_Call{Call: _e.mock.On("GetMonitoredHeadLength")}
}

func (_c *BlockListener_GetMonitoredHeadLength_Call) Run(run func()) *BlockListener_GetMonitoredHeadLength_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *BlockListener_GetMonitoredHeadLength_Call) Return(n int) *BlockListener_GetMonitoredHeadLength_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *BlockListener_GetMonitoredHeadLength_Call) RunAndReturn(run func() int) *BlockListener_GetMonitoredHeadLength_Call {
	_c.Call.Return(run)
	return _c
}

// InitMetrics provides a mock function for the type BlockListener
func (_mock *BlockListener) InitMetrics(ctx context.Context, registry metric.MetricsRegistry) error {
	ret := _mock.Called(ctx, registry)

	if len(ret) == 0 {
		panic("no return value specified for InitMetrics")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, metric.MetricsRegistry) error); ok {
		r0 = returnFunc(ctx, registry)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// BlockListener_InitMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitMetrics'
type BlockListener_InitMetrics_Call struct {
	*mock.Call
}

// InitMetrics is a helper method to define mock.On call
//   - ctx context.Context
//   - registry metric.MetricsRegistry
func (_e *BlockListener_Expecter) InitMetrics(ctx any, registry any) *BlockListener_InitMetrics_Call {
	return &BlockListener_InitMetrics_Call{Call: _e.mock.On("InitMetrics", ctx, registry)}
}

func (_c *BlockListener_InitMetrics_Call) Run(run func(ctx context.Context, registry metric.MetricsRegistry)) *BlockListener_InitMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 metric.MetricsRegistry
		if args[1] != nil {
			arg1 = args[1].(metric.MetricsRegistry)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *BlockListener_InitMetrics_Call) Return(err error) *BlockListener_InitMetrics_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *BlockListener_InitMetrics_Call) RunAndReturn(run func(ctx context.Context, registry metric.MetricsRegistry) error) *BlockListener_InitMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// ReconcileConfirmationsForTransaction provides a mock function for the type BlockListener
func (_mock *BlockListener) ReconcileConfirmationsForTransaction(ctx context.Context, txHash string, existingConfirmations []*ethrpc.MinimalBlockInfo, targetConfirmationCount uint64) (*ethblocklistener.ConfirmationUpdateResult, *ethrpc.TxReceiptJSONRPC, error) {
	ret := _mock.Called(ctx, txHash, existingConfirmations, targetConfirmationCount)

	if len(ret) == 0 {
		panic("no return value specified for ReconcileConfirmationsForTransaction")
	}

	var r0 *ethblocklistener.ConfirmationUpdateResult
	var r1 *ethrpc.TxReceiptJSONRPC
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []*ethrpc.MinimalBlockInfo, uint64) (*ethblocklistener.ConfirmationUpdateResult, *ethrpc.TxReceiptJSONRPC, error)); ok {
		return returnFunc(ctx, txHash, existingConfirmations, targetConfirmationCount)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []*ethrpc.MinimalBlockInfo, uint64) *ethblocklistener.ConfirmationUpdateResult); ok {
		r0 = returnFunc(ctx, txHash, existingConfirmations, targetConfirmationCount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ethblocklistener.ConfirmationUpdateResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []*ethrpc.MinimalBlockInfo, uint64) *ethrpc.TxReceiptJSONRPC); ok {
		r1 = returnFunc(ctx, txHash, existingConfirmations, targetConfirmationCount)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*ethrpc.TxReceiptJSONRPC)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, []*ethrpc.MinimalBlockInfo, uint64) error); ok {
		r2 = returnFunc(ctx, txHash, existingConfirmations, targetConfirmationCount)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// BlockListener_ReconcileConfirmationsForTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReconcileConfirmationsForTransaction'
type BlockListener_ReconcileConfirmationsForTransaction_Call struct {
	*mock.Call
}

// ReconcileConfirmationsForTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - txHash string
//   - existingConfirmations []*ethrpc.MinimalBlockInfo
//   - targetConfirmationCount uint64
func (_e *BlockListener_Expecter) ReconcileConfirmationsForTransaction(ctx any, txHash any, existingConfirmations any, targetConfirmationCount any) *BlockListener_ReconcileConfirmationsForTransaction_Call {
	return &BlockListener_ReconcileConfirmationsForTransaction_Call{Call: _e.mock.On("ReconcileConfirmationsForTransaction", ctx, txHash, existingConfirmations, targetConfirmationCount)}
}

func (_c *BlockListener_ReconcileConfirmationsForTransaction_Call) Run(run func(ctx context.Context, txHash string, existingConfirmations []*ethrpc.MinimalBlockInfo, targetConfirmationCount uint64)) *BlockListener_ReconcileConfirmationsForTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []*ethrpc.MinimalBlockInfo
		if args[2] != nil {
			arg2 = args[2].([]*ethrpc.MinimalBlockInfo)
		}
		var arg3 uint64
		if args[3] != nil {
			arg3 = args[3].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *BlockListener_ReconcileConfirmationsForTransaction_Call) Return(confirmationUpdateResult *ethblocklistener.ConfirmationUpdateResult, txReceiptJSONRPC *ethrpc.TxReceiptJSONRPC, err error) *BlockListener_ReconcileConfirmationsForTransaction_Call {
	_c.Call.Return(confirmationUpdateResult, txReceiptJSONRPC, err)
	return _c
}

func (_c *BlockListener_ReconcileConfirmationsForTransaction_Call) RunAndReturn(run func(ctx context.Context, txHash string, existingConfirmations []*ethrpc.MinimalBlockInfo, targetConfirmationCount uint64) (*ethblocklistener.ConfirmationUpdateResult, *ethrpc.TxReceiptJSONRPC, error)) *BlockListener_ReconcileConfirmationsForTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveConsumer provides a mock function for the type BlockListener
func (_mock *BlockListener) RemoveConsumer(ctx context.Context, id *fftypes.UUID) {
	_mock.Called(ctx, id)
	return
}

// BlockListener_RemoveConsumer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveConsumer'
type BlockListener_RemoveConsumer_Call struct {
	*mock.Call
}

// RemoveConsumer is a helper method to define mock.On call
//   - ctx context.Context
//   - id *fftypes.UUID
func (_e *BlockListener_Expecter) RemoveConsumer(ctx any, id any) *BlockListener_RemoveConsumer_Call {
	return &BlockListener_RemoveConsumer_Call{Call: _e.mock.On("RemoveConsumer", ctx, id)}
}

func (_c *BlockListener_RemoveConsumer_Call) Run(run func(ctx context.Context, id *fftypes.UUID)) *BlockListener_RemoveConsumer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *fftypes.UUID
		if args[1] != nil {
			arg1 = args[1].(*fftypes.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *BlockListener_RemoveConsumer_Call) Return() *BlockListener_RemoveConsumer_Call {
	_c.Call.Return()
	return _c
}

func (_c *BlockListener_RemoveConsumer_Call) RunAndReturn(run func(ctx context.Context, id *fftypes.UUID)) *BlockListener_RemoveConsumer_Call {
	_c.Run(run)
	return _c
}

// SnapshotMonitoredHeadChain provides a mock function for the type BlockListener
func (_mock *BlockListener) SnapshotMonitoredHeadChain() []*ethrpc.BlockInfoJSONRPC {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SnapshotMonitoredHeadChain")
	}

	var r0 []*ethrpc.BlockInfoJSONRPC
	if returnFunc, ok := ret.Get(0).(func() []*ethrpc.BlockInfoJSONRPC); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ethrpc.BlockInfoJSONRPC)
		}
	}
	return r0
}

// BlockListener_SnapshotMonitoredHeadChain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SnapshotMonitoredHeadChain'
type BlockListener_SnapshotMonitoredHeadChain_Call struct {
	*mock.Call
}

// SnapshotMonitoredHeadChain is a helper method to define mock.On call
func (_e *BlockListener_Expecter) SnapshotMonitoredHeadChain() *BlockListener_SnapshotMonitoredHeadChain_Call {
	return &BlockListener_SnapshotMonitoredHeadChain_Call{Call: _e.mock.On("SnapshotMonitoredHeadChain")}
}

func (_c *BlockListener_SnapshotMonitoredHeadChain_Call) Run(run func()) *BlockListener_SnapshotMonitoredHeadChain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *BlockListener_SnapshotMonitoredHeadChain_Call) Return(blockInfoJSONRPCs []*ethrpc.BlockInfoJSONRPC) *BlockListener_SnapshotMonitoredHeadChain_Call {
	_c.Call.Return(blockInfoJSONRPCs)
	return _c
}

func (_c *BlockListener_SnapshotMonitoredHeadChain_Call) RunAndReturn(run func() []*ethrpc.BlockInfoJSONRPC) *BlockListener_SnapshotMonitoredHeadChain_Call {
	_c.Call.Return(run)
	return _c
}

// WaitClosed provides a mock function for the type BlockListener
func (_mock *BlockListener) WaitClosed() {
	_mock.Called()
	return
}

// BlockListener_WaitClosed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitClosed'
type BlockListener_WaitClosed_Call struct {
	*mock.Call
}

// WaitClosed is a helper method to define mock.On call
func (_e *BlockListener_Expecter) WaitClosed() *BlockListener_WaitClosed_Call {
	return &BlockListener_WaitClosed_Call{Call: _e.mock.On("WaitClosed")}
}

func (_c *BlockListener_WaitClosed_Call) Run(run func()) *BlockListener_WaitClosed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *BlockListener_WaitClosed_Call) Return() *BlockListener_WaitClosed_Call {
	_c.Call.Return()
	return _c
}

func (_c *BlockListener_WaitClosed_Call) RunAndReturn(run func()) *BlockListener_WaitClosed_Call {
	_c.Run(run)
	return _c
}
