// Code generated by mockery v2.53.5. DO NOT EDIT.

package ethblocklistenermocks

import (
	context "context"

	ethblocklistener "github.com/hyperledger/firefly-evmconnect/pkg/ethblocklistener"
	ethrpc "github.com/hyperledger/firefly-evmconnect/pkg/ethrpc"

	ethtypes "github.com/hyperledger/firefly-signer/pkg/ethtypes"

	ffcapi "github.com/hyperledger/firefly-transaction-manager/pkg/ffcapi"

	fftypes "github.com/hyperledger/firefly-common/pkg/fftypes"

	mock "github.com/stretchr/testify/mock"

	rpcbackend "github.com/hyperledger/firefly-signer/pkg/rpcbackend"
)

// BlockListener is an autogenerated mock type for the BlockListener type
type BlockListener struct {
	mock.Mock
}

// AddConsumer provides a mock function with given fields: ctx, c
func (_m *BlockListener) AddConsumer(ctx context.Context, c *ethblocklistener.BlockUpdateConsumer) {
	_m.Called(ctx, c)
}

// FetchBlockReceiptsAsync provides a mock function with given fields: blockNumber, blockHash, cb
func (_m *BlockListener) FetchBlockReceiptsAsync(blockNumber uint64, blockHash ethtypes.HexBytes0xPrefix, cb func([]*ethrpc.TxReceiptJSONRPC, error)) {
	_m.Called(blockNumber, blockHash, cb)
}

// GetBackend provides a mock function with no fields
func (_m *BlockListener) GetBackend() rpcbackend.RPC {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBackend")
	}

	var r0 rpcbackend.RPC
	if rf, ok := ret.Get(0).(func() rpcbackend.RPC); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(rpcbackend.RPC)
		}
	}

	return r0
}

// GetBlockInfoByHash provides a mock function with given fields: ctx, hash0xString
func (_m *BlockListener) GetBlockInfoByHash(ctx context.Context, hash0xString string) (*ethrpc.BlockInfoJSONRPC, error) {
	ret := _m.Called(ctx, hash0xString)

	if len(ret) == 0 {
		panic("no return value specified for GetBlockInfoByHash")
	}

	var r0 *ethrpc.BlockInfoJSONRPC
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*ethrpc.BlockInfoJSONRPC, error)); ok {
		return rf(ctx, hash0xString)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *ethrpc.BlockInfoJSONRPC); ok {
		r0 = rf(ctx, hash0xString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ethrpc.BlockInfoJSONRPC)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, hash0xString)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBlockInfoByNumber provides a mock function with given fields: ctx, blockNumber, allowCache, expectedParentHashStr, expectedBlockHashStr
func (_m *BlockListener) GetBlockInfoByNumber(ctx context.Context, blockNumber uint64, allowCache bool, expectedParentHashStr string, expectedBlockHashStr string) (*ethrpc.BlockInfoJSONRPC, error) {
	ret := _m.Called(ctx, blockNumber, allowCache, expectedParentHashStr, expectedBlockHashStr)

	if len(ret) == 0 {
		panic("no return value specified for GetBlockInfoByNumber")
	}

	var r0 *ethrpc.BlockInfoJSONRPC
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, bool, string, string) (*ethrpc.BlockInfoJSONRPC, error)); ok {
		return rf(ctx, blockNumber, allowCache, expectedParentHashStr, expectedBlockHashStr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, bool, string, string) *ethrpc.BlockInfoJSONRPC); ok {
		r0 = rf(ctx, blockNumber, allowCache, expectedParentHashStr, expectedBlockHashStr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ethrpc.BlockInfoJSONRPC)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, bool, string, string) error); ok {
		r1 = rf(ctx, blockNumber, allowCache, expectedParentHashStr, expectedBlockHashStr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEVMBlockWithTransactionsByHash provides a mock function with given fields: ctx, hash0xString
func (_m *BlockListener) GetEVMBlockWithTransactionsByHash(ctx context.Context, hash0xString string) (*ethrpc.EVMBlockWithTransactionsJSONRPC, error) {
	ret := _m.Called(ctx, hash0xString)

	if len(ret) == 0 {
		panic("no return value specified for GetEVMBlockWithTransactionsByHash")
	}

	var r0 *ethrpc.EVMBlockWithTransactionsJSONRPC
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*ethrpc.EVMBlockWithTransactionsJSONRPC, error)); ok {
		return rf(ctx, hash0xString)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *ethrpc.EVMBlockWithTransactionsJSONRPC); ok {
		r0 = rf(ctx, hash0xString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ethrpc.EVMBlockWithTransactionsJSONRPC)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, hash0xString)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEVMBlockWithTransactionsByNumber provides a mock function with given fields: ctx, numberLookup
func (_m *BlockListener) GetEVMBlockWithTransactionsByNumber(ctx context.Context, numberLookup string) (*ethrpc.EVMBlockWithTransactionsJSONRPC, error) {
	ret := _m.Called(ctx, numberLookup)

	if len(ret) == 0 {
		panic("no return value specified for GetEVMBlockWithTransactionsByNumber")
	}

	var r0 *ethrpc.EVMBlockWithTransactionsJSONRPC
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*ethrpc.EVMBlockWithTransactionsJSONRPC, error)); ok {
		return rf(ctx, numberLookup)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *ethrpc.EVMBlockWithTransactionsJSONRPC); ok {
		r0 = rf(ctx, numberLookup)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ethrpc.EVMBlockWithTransactionsJSONRPC)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, numberLookup)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEVMBlockWithTxHashesByHash provides a mock function with given fields: ctx, hash0xString
func (_m *BlockListener) GetEVMBlockWithTxHashesByHash(ctx context.Context, hash0xString string) (*ethrpc.EVMBlockWithTxHashesJSONRPC, error) {
	ret := _m.Called(ctx, hash0xString)

	if len(ret) == 0 {
		panic("no return value specified for GetEVMBlockWithTxHashesByHash")
	}

	var r0 *ethrpc.EVMBlockWithTxHashesJSONRPC
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*ethrpc.EVMBlockWithTxHashesJSONRPC, error)); ok {
		return rf(ctx, hash0xString)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *ethrpc.EVMBlockWithTxHashesJSONRPC); ok {
		r0 = rf(ctx, hash0xString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ethrpc.EVMBlockWithTxHashesJSONRPC)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, hash0xString)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEVMBlockWithTxHashesByNumber provides a mock function with given fields: ctx, numberLookup
func (_m *BlockListener) GetEVMBlockWithTxHashesByNumber(ctx context.Context, numberLookup string) (*ethrpc.EVMBlockWithTxHashesJSONRPC, error) {
	ret := _m.Called(ctx, numberLookup)

	if len(ret) == 0 {
		panic("no return value specified for GetEVMBlockWithTxHashesByNumber")
	}

	var r0 *ethrpc.EVMBlockWithTxHashesJSONRPC
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*ethrpc.EVMBlockWithTxHashesJSONRPC, error)); ok {
		return rf(ctx, numberLookup)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *ethrpc.EVMBlockWithTxHashesJSONRPC); ok {
		r0 = rf(ctx, numberLookup)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ethrpc.EVMBlockWithTxHashesJSONRPC)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, numberLookup)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetHighestBlock provides a mock function with given fields: ctx
func (_m *BlockListener) GetHighestBlock(ctx context.Context) (uint64, bool) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetHighestBlock")
	}

	var r0 uint64
	var r1 bool
	if rf, ok := ret.Get(0).(func(context.Context) (uint64, bool)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) uint64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) bool); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// GetMonitoredHeadLength provides a mock function with no fields
func (_m *BlockListener) GetMonitoredHeadLength() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMonitoredHeadLength")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// ReconcileConfirmationsForTransaction provides a mock function with given fields: ctx, txHash, existingConfirmations, targetConfirmationCount
func (_m *BlockListener) ReconcileConfirmationsForTransaction(ctx context.Context, txHash string, existingConfirmations []*ffcapi.MinimalBlockInfo, targetConfirmationCount uint64) (*ffcapi.ConfirmationUpdateResult, *ethrpc.TxReceiptJSONRPC, error) {
	ret := _m.Called(ctx, txHash, existingConfirmations, targetConfirmationCount)

	if len(ret) == 0 {
		panic("no return value specified for ReconcileConfirmationsForTransaction")
	}

	var r0 *ffcapi.ConfirmationUpdateResult
	var r1 *ethrpc.TxReceiptJSONRPC
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []*ffcapi.MinimalBlockInfo, uint64) (*ffcapi.ConfirmationUpdateResult, *ethrpc.TxReceiptJSONRPC, error)); ok {
		return rf(ctx, txHash, existingConfirmations, targetConfirmationCount)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []*ffcapi.MinimalBlockInfo, uint64) *ffcapi.ConfirmationUpdateResult); ok {
		r0 = rf(ctx, txHash, existingConfirmations, targetConfirmationCount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ffcapi.ConfirmationUpdateResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []*ffcapi.MinimalBlockInfo, uint64) *ethrpc.TxReceiptJSONRPC); ok {
		r1 = rf(ctx, txHash, existingConfirmations, targetConfirmationCount)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*ethrpc.TxReceiptJSONRPC)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, []*ffcapi.MinimalBlockInfo, uint64) error); ok {
		r2 = rf(ctx, txHash, existingConfirmations, targetConfirmationCount)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// RemoveConsumer provides a mock function with given fields: ctx, id
func (_m *BlockListener) RemoveConsumer(ctx context.Context, id *fftypes.UUID) {
	_m.Called(ctx, id)
}

// SnapshotMonitoredHeadChain provides a mock function with no fields
func (_m *BlockListener) SnapshotMonitoredHeadChain() []*ethrpc.BlockInfoJSONRPC {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SnapshotMonitoredHeadChain")
	}

	var r0 []*ethrpc.BlockInfoJSONRPC
	if rf, ok := ret.Get(0).(func() []*ethrpc.BlockInfoJSONRPC); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ethrpc.BlockInfoJSONRPC)
		}
	}

	return r0
}

// UTSetBackend provides a mock function with given fields: _a0
func (_m *BlockListener) UTSetBackend(_a0 rpcbackend.RPC) {
	_m.Called(_a0)
}

// WaitClosed provides a mock function with no fields
func (_m *BlockListener) WaitClosed() {
	_m.Called()
}

// NewBlockListener creates a new instance of BlockListener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBlockListener(t interface {
	mock.TestingT
	Cleanup(func())
}) *BlockListener {
	mock := &BlockListener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
